### ISSUE TITLE
Invalid Entry content_type_uid

### ISSUE THREAD

**Issue by MBO** [contentstack/contentstack-management-javascript#10]
This line always sets `content_type_uid` as literal `'uid'`:

https://github.com/contentstack/contentstack-management-javascript/blob/3850278886114011665c3c2d5d5ef9044959853e/lib/stack/contentType/entry/index.js#L274

Because of that it's not possible to use this library functions: `entry.update()`, `entry.publish()` and so on, because they have invalid `urlPath`.

**Comment by uttamukkoji** [comment]
Thanks for raising issue @MBO, We will work on the issue and update here once we are done with the changes.
