### ISSUE TITLE
Cannot convert undefined or null to object on 'cleanAssets' function

### ISSUE THREAD

**Issue by carlos-lopez-kc** [contentstack/contentstack-management-javascript#104]
Hey CS Team, 

I noticed a unexpected behavior with the recent version that were released (`1.14.0`) and seems that the new function called 'cleanAssets' are validating a value can be a `null` as type of object but can't be used with the method `Object.keys` this is the following block:

### This is the following block of code referenced:

https://github.com/contentstack/contentstack-management-javascript/blob/5f6878ca8e50e7a50cbae1ad0b15c84a0a5dc7bc/lib/entity.js#L320

1. A `null` value also can be a "object" type
2. A `null` value can't be used on `Object.keys` because will throw the following error:

![image](https://github.com/contentstack/contentstack-management-javascript/assets/132929400/b9c41117-4cc9-4c67-bad7-2a22fe08ac11)

Node.js Version: v20.9.0
OS: Ubuntu v20.04

**Comment by sunil-lakshman** [comment]
> Hey CS Team,
> 
> I noticed a unexpected behavior with the recent version that were released (`1.14.0`) and seems that the new function called 'cleanAssets' are validating a value can be a `null` as type of object but can't be used with the method `Object.keys` this is the following block:
> 
> ### This is the following block of code referenced:
> https://github.com/contentstack/contentstack-management-javascript/blob/5f6878ca8e50e7a50cbae1ad0b15c84a0a5dc7bc/lib/entity.js#L320
> 
> 1. A `null` value also can be a "object" type
> 2. A `null` value can't be used on `Object.keys` because will throw the following error:
> 
> ![image](https://private-user-images.githubusercontent.com/132929400/294065202-b9c41117-4cc9-4c67-bad7-2a22fe08ac11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODg2NTksIm5iZiI6MTcwNjA4ODM1OSwicGF0aCI6Ii8xMzI5Mjk0MDAvMjk0MDY1MjAyLWI5YzQxMTE3LTRjYzktNGM2Ny1iYWQ3LTJhMjJmZTA4YWMxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQwOTI1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGNlY2JkYzY5Y2RhNjZiNGU1N2Q2NDdjYjgyM2ZkMzBjMTQ3MDQwZDM0NjI2M2ZhYjg5YmRiMWE2ZDQxYjk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QpEKlciUgnMQMO5X5AVa68gsjkz7SOG80St1Nt-uLe8)
> 
> Node.js Version: v20.9.0 OS: Ubuntu v20.04

Issue has been fixed in v1.15.0

**Comment by mato84** [comment]
Hello @sunil-lakshman, I hope you're doing well. I wanted to check in regarding the status of the bug fixes. Are there any updates on when we can expect them to be resolved? I'm eager to update the Entities but need these issues addressed first.
I asked this because version 15 was already realised but this commit was not merged

**Comment by harshithad0703** [comment]
Hai @mato84, I hope you are doing well too. 
The fix is released in version **1.15.3**, let us know if there's anything further required.

cc: @sunil-lakshman

**Comment by mato84** [comment]
@harshithad0703 thanks for the update
