### ISSUE TITLE
Not possible to upload by URL?

### ISSUE THREAD

**Issue by MagnusHJensen** [contentstack/contentstack-management-javascript#107]
Trying the following:

```typescript
const fileUrl = getPresignedS3Url(...);

const image = await this.stack.asset().create({
      title: "My Image",
      upload: fileUrl,
    });
```
Does not work? `Cannot read properties of undefined (reading: 'retryCount')

_Version: 1.10.2_

**Comment by sunil-lakshman** [comment]
Hi @MagnusHJensen, Contentstack API and SDK supports only direct file uploads.

**Comment by MagnusHJensen** [comment]
That is fair, maybe a better user error would be nicer?

So check if the passed in value is a string, and matches a URL regex, and then throw an error saying URL uploads is not supported? Instead of failing on a runtime error, due to retrying.

**Comment by sunil-lakshman** [comment]
Noted @MagnusHJensen, We will check and sending a proper error messages.
