### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by jakelauer** [contentstack/contentstack-management-javascript#13]
Is TypeScript support a possibility with this library?

**Comment by uttamukkoji** [comment]
Hi @jakelauer,

Currently we do not have TypeDefinition in library, we have this feature request in our backlog. We are planning to release type definition files by July.

**Comment by jakelauer** [comment]
Great!

**Comment by lyleunderwood** [comment]
Any update on this?

**Comment by sdailly** [comment]
Any update ? 
thx

**Comment by kamil-alekber** [comment]
oh, still no updates. will have to create my own definition file. will share it with the community later.

**Comment by uttamukkoji** [comment]
@jakelauer @sdailly and @kamil-alekber we have added TypeDefinitions to support TypeScripts in **v1.3.1**.
