### ISSUE TITLE
Server-side Request Forgery (SSRF) in @contentstack/management@1.17.0 via axios@1.7.3

### ISSUE THREAD

**Issue by GlebShulga** [contentstack/contentstack-management-javascript#173]
Snyk found a vulnerability in @contentstack/management@1.17.0 via axios@1.7.3.

Is a fix planned for the near future?

![Screenshot 2024-08-13 164517](https://github.com/user-attachments/assets/06a560a0-c283-48fd-a439-a4d3e064b852)

**Comment by cs-raj** [comment]
Hi @GlebShulga it was done with v1.17.1
Closing the issue
cc: @netrajpatel  @shafeeqd959
