### ISSUE TITLE
support for EU region

### ISSUE THREAD

**Issue by pveller** [contentstack/contentstack-management-javascript#32]
it looks like there's no "easy" way to point to a EU region like what you do in the delivery API. 

In delivery API, you can supply `{ region: Region.EU }` when create your `Stack`.

In management API, you need to overwrite `defaultHostName` here: https://github.com/contentstack/contentstack-management-javascript/blob/dd3294bf51717f1f8c30b46280578961829bcee4/lib/contentstack.js#L182 and use `eu-api.contentstack.com`. 

Is this an oversight or am I missing something? I see no reference in `region` anywhere in the code. An attempt to use the SDK with our EU stacks results in:

```
{
  "errorMessage":"We can't find that Stack. Please try again.",
  "errorCode":109,
  "errors":{"api_key":["is not valid."] }
}
```

**Comment by sxurik** [comment]
Setting a region in delivery api like this:
```ts
export const client = contentstack
  .client({
    host: 'eu-api.contentstack.com',
  });
```
seems like a better idea. No overriding of default values this way.

But it does seem strange, that delivery api and management api provide different ways to choose a region.
And the [docs for management api](https://www.contentstack.com/docs/developers/javascript-management/api-reference/Contentstack.html) are very vague on this `host` property. Whereas there is a clear explanation on how to set a different region in [delivery api docs](https://www.contentstack.com/docs/developers/javascript-browser/api-reference/).

**Comment by ishaileshmishra** [comment]
Thanks for writing us @sxurik, We are looking into it.
