### ISSUE TITLE
Incorrect input type for bulk delete operation

### ISSUE THREAD

**Issue by michauds** [contentstack/contentstack-management-javascript#46]
The exported interface for delete on bulkOperation (https://github.com/contentstack/contentstack-management-javascript/blob/master/types/stack/bulkOperation/index.d.ts#L8) should include a named attribute "details" to contain the interface BulkDeleteConfig.

The delete operation (https://github.com/contentstack/contentstack-management-javascript/blob/master/lib/stack/bulkOperation/index.js#L209) expects it.

**Comment by uttamukkoji** [comment]
Thanks @michauds for raising the issue, we will work on this and let you know once we release fix for the issue.

**Comment by cs-raj** [comment]
HI @michauds we will be taking this issue in the upcoming sprint and let you know once the fix is released
cc: @netrajpatel @sunil-lakshman @shafeeqd959

**Comment by vkalta** [comment]
This has already been fixed @cs-raj. Hence closing this.
