### ISSUE TITLE
Library not intended for use in a browser?

### ISSUE THREAD

**Issue by aweber1** [contentstack/contentstack-management-javascript#5]
Hello,

I'm trying to integrate this library into an application that is running in the browser. However, there are Node module dependencies  preventing that from happening. In particular, the `fs` module.

`import contentstack from '@contentstack/management';`

results in a `Module note found: can't resolve 'fs'` error message.

I have verified that the `import` statement is resolving to `node_modules/@contentstack/management/dist/web/contentstack-management.js`. However, it appears that the `web` version of the library build contains a `require("fs")` statement.

Is this library not intended for use in a browser? If so, I would recommend clearly stating that in the readme. However, if it _is_ intended to be used in the browser, I think some refactoring may be in order to remove the dependencies on Node core modules.

**Comment by uttamukkoji** [comment]
Hello @aweber1 ,

We do not recommend to used this library in browser. We will update the readme file with note stating not supported for browser. Thanks for the raising this issue and helping us to improve this library.

**Comment by aweber1** [comment]
Ok, thank you!

**Comment by uttamukkoji** [comment]
Closing this issue as there is no support for in browser.
