### ISSUE TITLE
Undeclared function delete for Asset and Assets interfaces

### ISSUE THREAD

**Issue by aarguelles93** [contentstack/contentstack-management-javascript#51]
When trying to use the .detele() function for an instance of Asset, as defined in the [sdk documentation](https://www.contentstack.com/docs/developers/sdks/content-management-sdk/javascript/reference/#asset-delete), linter raises an error stating that "Property 'delete' does not exist on type 'Asset | Assets'.".

**Comment by sunil-lakshman** [comment]
Below code is working fine.
```
import contentstack from "@contentstack/management";
const client = contentstack.client({host: 'HOST', authtoken: 'AUTHTOKEN'});
client.stack({ api_key: 'API_KEY'}).asset('ASSET_UID')
.delete()
.then((response) => console.log(response.notice))

```
